### ISSUE TITLE
Editing website style

### ISSUE THREAD

**Issue by stineb** [geco-bern/geco_website#3]
Looks great already. Here are a few changes I wanted to implement. I tried to do it myself but utterly failed. You can either point me to where to do this or implement it directly. My suggested edits are:

- [x] Menu bar background color to geco-style brownish (#777055ff)
- [x] Helvetica bold font for all all headings. Roboto for main text.
- [x] Logo in upper left corner (inside the menu bar)
- [x] First content on home: Slider widget like on bluegreenlabs.org with three pictures and our mission text on top of the picture in this order:
   1. _We develop capacity to detect, quantify, and predict responses of plants and ecosystems to climate change and forecast the impact of extremes._ Use photo which is currently the banner photo.
   2. _We are a team of researchers driven by our curiosity to understand how the terrestrial biosphere operates._ Use our group picture.
   3. _Our science enables a better understanding of the integrity and function of the natural world under pressure - key to creating a sustainable future._ Use picture `jungle.jpg`.
- [x] Second content on home: A bar stating that we're a group at GIUB, UniBe and Oeschger Centre. Ideally with their logos.
- [x] Third content on home: projects widget
- [x] Fourth content on home: Featured publications

**Comment by stineb** [comment]
I haven't managed to display the geco logo in the navigation bar (top-left, next to 'Geocomputation ...'). I've saved a 512x512 px as `assets/media/icon.png` and I've set `show_logo: true` in `params.yaml`. No success and no more ideas...

**Comment by khufkens** [comment]
Icon fixed, reduced image sizes to increase page loading times. See to it that maximum image sizes are not larger than 1600px wide and ~500kb in size (preferably ~200kb).

The logos "block" is a paying feature in the wowchemy software as a service setup. I hacked together as simple page with a combined logo - needs to be reworked. In absence of the old widget pages, and the fracture intentional lack of transparency of the platform this is the best I can do.

**Comment by stineb** [comment]
@khufkens This looks awesome now. Thanks a lot!

**Comment by khufkens** [comment]
Thanks. The wowchemy stuff is a bit of a pain really, if you want to go further than the default (rather ugly) theme. I know remember why I stick to the old version. It wasn't only licensing, it has become intentionally unreadable to squeeze users for a buck.
